/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.gradle.db.test;


import javax.annotation.Generated;

import org.jooq.example.gradle.db.test.tables.Author;
import org.jooq.example.gradle.db.test.tables.Book;
import org.jooq.example.gradle.db.test.tables.BookStore;
import org.jooq.example.gradle.db.test.tables.BookToBookStore;
import org.jooq.example.gradle.db.test.tables.Language;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.author</code>.
     */
    public static final Author AUTHOR = org.jooq.example.gradle.db.test.tables.Author.AUTHOR;

    /**
     * The table <code>test.book</code>.
     */
    public static final Book BOOK = org.jooq.example.gradle.db.test.tables.Book.BOOK;

    /**
     * The table <code>test.book_store</code>.
     */
    public static final BookStore BOOK_STORE = org.jooq.example.gradle.db.test.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>test.book_to_book_store</code>.
     */
    public static final BookToBookStore BOOK_TO_BOOK_STORE = org.jooq.example.gradle.db.test.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>test.language</code>.
     */
    public static final Language LANGUAGE = org.jooq.example.gradle.db.test.tables.Language.LANGUAGE;
}
