/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.gradle.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Schema;
import org.jooq.example.gradle.db.information_schema.InformationSchema;
import org.jooq.example.gradle.db.mysql.Mysql;
import org.jooq.example.gradle.db.performance_schema.PerformanceSchema;
import org.jooq.example.gradle.db.sys.Sys;
import org.jooq.example.gradle.db.test.Test;
import org.jooq.impl.CatalogImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = 783479180;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * The schema <code>information_schema</code>.
     */
    public final InformationSchema INFORMATION_SCHEMA = org.jooq.example.gradle.db.information_schema.InformationSchema.INFORMATION_SCHEMA;

    /**
     * The schema <code>mysql</code>.
     */
    public final Mysql MYSQL = org.jooq.example.gradle.db.mysql.Mysql.MYSQL;

    /**
     * The schema <code>performance_schema</code>.
     */
    public final PerformanceSchema PERFORMANCE_SCHEMA = org.jooq.example.gradle.db.performance_schema.PerformanceSchema.PERFORMANCE_SCHEMA;

    /**
     * The schema <code>sys</code>.
     */
    public final Sys SYS = org.jooq.example.gradle.db.sys.Sys.SYS;

    /**
     * The schema <code>test</code>.
     */
    public final Test TEST = org.jooq.example.gradle.db.test.Test.TEST;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        List result = new ArrayList();
        result.addAll(getSchemas0());
        return result;
    }

    private final List<Schema> getSchemas0() {
        return Arrays.<Schema>asList(
            InformationSchema.INFORMATION_SCHEMA,
            Mysql.MYSQL,
            PerformanceSchema.PERFORMANCE_SCHEMA,
            Sys.SYS,
            Test.TEST);
    }
}
